# -*- coding: utf-8 -*-

print("----------------------------------------------------------------")
print("----------------------------------------------------------------")
print('{:^65}'.format(' ---Shop--- '))
print("\n\n")
print('{:^65}'.format('<--Item-->'))
print("\n\n")
print("Powerade - HP +5: 5 Gold")
print("\n")
print("Cola - Recover 10% of your Max HP in five turns: 5 Gold")
print("\n")
print("Energe Drink - Damage increases by 5%: 7 Gold")
print("\n")
print("TWO Soju - Make your HP 1, but you don't get damage next turn: 15 Gold")
print("\n")
print("")