# -- coding: utf-8 --

print("----------------------------------------------------------------")
print("----------------------------------------------------------------")
print("\n")
print('{:^65}'.format(' -----Shop----- '))
print("\n\n")
print('{:^65}'.format('<--Item-->'))
print("\n Prev --- P \n Next --- N \n Back --- B")
print("\n\n")
print("1:Powerade - Recover HP +5: 5Gold")
print("\n")
print("2:Cola - Recover 50% of your Max HP: 5Gold")
print("\n")
print("3:Energe Drink - Damage increases by 5%: 7Gold")
print("\n")
print("4:TWO Soju - Make your HP 1, but you don't get damage next turn: 15Gold")
print("\n")
print("5:Stick Icecream - Increas Defensice power 5%: 5Gold")
print("\n")
print("6:Corn Icecream - Recover HP +5 but reducing Evasion by 5% over the next turn: 7Gold")
print("\n")
print("7:Potato Chip - Reducing monster's Evasion by 10% next 2 turns: 5Gold")
print("\n")
print("8:Lollipop - Max HP and Defensice power increases by 1: 5Gold")
print("\n")
print("9:Small Chocolate - Increases Offensive power by 1: 5Gold")
print("10:Medium Chocolate - Increases Offensive power by 2: 7Gold")
print("11:Big Chocolate - Increases Offensive power by 3: 9Gold")
print("\n")
print("12:Stockings - Increases Evasion 10%: 10Gold")
print("\n")
print("13:Plastic Bag - Increases Bag size 1: 15Gold")
print("\n")
print("----------------------------------------------------------------")
print('{:^65}'.format(' -----1/2----- '))
print("\n")
print("----------------------------------------------------------------")
print("----------------------------------------------------------------")
print("\n\n\n")
print("----------------------------------------------------------------")
print("----------------------------------------------------------------")
print("\n")
print('{:^65}'.format(' -----Shop----- '))
print("\n\n")
print('{:^65}'.format('<--Weapon-->'))
print("\n Prev --- P \n Next --- N \n Back --- B")
print("\n\n")
print("Baisic Weapon")
print("\n")
print("1:Pocket Knife - Made in China: ATK 2")
print("2:Cutter knife - The blade breaks easily: ATK 10 (if it breaks 1)")
print("\n")
print("3:Slingshot - Monster's Evation +10%:90Gold, ATK 12")
print("\n")
print("4:Coin - Ammunition for a slingshot:1Gold each")
print("\n")
print("5:Cardboard Box - Ignore any damage: 35Gold")
print("\n")
print("6:A Big Mop - Swing to attack: 70Gold, ATK 7")
print("\n")
print("7:Light Bar - Once used, it will be break: 300Gold, ATK 50")
print("\n")
print("8:Scissor - 5% chance to debuff -1 HP when you hit monster: 30Gold, ATK 3")
print("\n")
print("9:Wallet - When you hold Wallet you can get 10% more Gold: 20Gold")
print("\n")
print("10:Key - You have 1% chance to attack fatal damage: 50Gold, ATK 1~100")
print("\n")
print("11:Butain - When your throw damage 25% HP to monster")
print("\n")
print("----------------------------------------------------------------")
print('{:^65}'.format('-----2/2-----'))
print("\n")
print("----------------------------------------------------------------")
print("----------------------------------------------------------------")
