# -- coding: utf-8 --

print("----------------------------------------------------------------")
print("----------------------------------------------------------------")
print('{:^65}'.format(' ---Shop--- '))
print("\n\n")
print('{:^65}'.format('<--Item-->'))
print("\n\n")
print("Powerade - REcover HP +5: 5Gold")
print("\n")
print("Cola - Recover 50 of your Max HP: 5Gold")
print("\n")
print("Energe Drink - Damage increases by 5: 7Gold")
print("\n")
print("TWO Soju - Make your HP 1, but you don't get damage next turn: 15Gold")
print("\n")
print("Stick Icecream - Increas Defensice power 5%: 5Gold")
print("\n")
print("Corn Icecream - Recover HP +5 but reducing avoidance rates by 5% over the next turn: 7Gold")
print("\n")
print("Potato Chip - Reducing monster's avoidence rates by 10% next 2 turns: 5Gold")
print("\n")
print("Lollipop - Max HP and Defensice power increases by one: 5Gold")
print("\n")
print("Small Chocolate - Increases Offensive power by 1: 5Gold")
print("Medium Chocolate - Increases Offensive power by 2: 7Gold")
print("Big Chocolate - Increases Offensive power by 3: 9Gold")
print("\n")
print("Butane - 
