# -- coding: utf-8 --

print("----------------------------------------------------------------")
print("----------------------------------------------------------------")
print("\n")
print('{:^65}'.format(' -----Shop----- '))
print("\n\n")
print('{:^65}'.format('<--Item-->'))
print("\n Prev --- P \n Next --- N \n Back --- B")
print("\n\n")
print("Powerade - Recover HP +5: 5Gold")
print("\n")
print("Cola - Recover 50% of your Max HP: 5Gold")
print("\n")
print("Energe Drink - Damage increases by 5%: 7Gold")
print("\n")
print("TWO Soju - Make your HP 1, but you don't get damage next turn: 15Gold")
print("\n")
print("Stick Icecream - Increas Defensice power 5%: 5Gold")
print("\n")
print("Corn Icecream - Recover HP +5 but reducing Evasion by 5% over the next turn: 7Gold")
print("\n")
print("Potato Chip - Reducing monster's Evasion by 10% next 2 turns: 5Gold")
print("\n")
print("Lollipop - Max HP and Defensice power increases by 1: 5Gold")
print("\n")
print("Small Chocolate - Increases Offensive power by 1: 5Gold")
print("Medium Chocolate - Increases Offensive power by 2: 7Gold")
print("Big Chocolate - Increases Offensive power by 3: 9Gold")
print("\n")
print("Stockings - Increases Evasion 10%: 10Gold")
print("\n")
print("Plastic Bag - Increases Bag size 1: 15Gold")
print("\n")
print("----------------------------------------------------------------")
print('{:^65}'.format(' -----1/2----- '))
print("\n")
print("----------------------------------------------------------------")
print("----------------------------------------------------------------")
print("\n\n\n")
print("----------------------------------------------------------------")
print("----------------------------------------------------------------")
print("\n")
print('{:^65}'.format(' -----Shop----- '))
print("\n\n")
print('{:^65}'.format('<--Weapon-->'))
print("\n Prev --- P \n Next --- N \n Back --- B")
print("\n\n")
print("Baisic Weapon")
print("\n")
print("Pocket Knife - Made in China: ATK 2")
print("Cutter knife - The blade breaks easily: ATK 10 (if it breaks 1)")
print("\n")
print("Slingshot - Monster's Evation +10%:90Gold, ATK 12")
print("\n")
print("Coin - Ammunition for a slingshot:1Gold each")
print("\n")
print("Cardboard Box - Ignore any damage: 35Gold")
print("\n")
print("A Big Mop - Swing to attack: 70Gold, ATK 7")
print("Light Bar - Once used, it will be break: 300Gold, ATK 50")
print("\n")
print("Scissor - 5% chance to debuff -1 HP when you hit monster: 30Gold, ATK 3")
print("\n")
print("Wallet - When you hold Wallet you can get 10% more Gold: 20Gold")
print("\n")
print("Key - You have 1% chance to attack fatal damage: 50Gold, ATK 1~100")
print("\n")
print("----------------------------------------------------------------")
print('{:^65}'.format('-----2/2-----'))
print("\n")
print("----------------------------------------------------------------")
print("----------------------------------------------------------------")
